### PR TITLE
Add tsd "rebundle" command support

### PR DESCRIPTION
**Pull request by KarlDirck**
Added "rebundle" command which calls API.updateBundle similarly to how
CLI.rebundle works.

### CODE REVIEW

**Comment by moznion** [comment]
Sorry for my late merging. Thanks a lot!

**Comment by moznion** [comment]
@KarlDirck 
v0.1.1 is out now :beer:

**Comment by KarlDirck** [comment]
Thank you.

**Comment by KarlDirck** [comment]
@moznion  Would you mind publishing a npm of this version?

**Comment by moznion** [comment]
It has been already available (v0.1.1) :D

**Pull request merged**
